### ISSUE TITLE
[BUG] ClassNotFoundException, it tried to find obc.v1_19_R1, but the package in server is obc.v1_19_R2.

### ISSUE THREAD

**Issue by qyl27** [Pante/chimera#458]
**Describe the bug**
It caused a no classdef error.  
When I use chimera on paper 1.19.3, it tried to find obc.v1_19_R1, but the package in server is obc.v1_19_R2.  
In the latest 5.4.2-SNAPSHOT of chimera, it still can be reproduced.

**To Reproduce**
1. Follow the wiki, I wrote some code.
2. Use papermake plugin to run a paper server.
3. `Dispatcher.of(JavaPlugin)` got ClassNotFoundException.

**Expected behavior**
It should run correctly.

**Environment (please complete the following information):**
 - Java Version: 17
 - Platform: Paper
 - Platform Version: 1.19.3 build 426
 - Chimera Version: 5.4.2-SNAPSHOT

**Additional context**
Some logs:  
```
[08:01:08 ERROR]: Error occurred while enabling AlchemyIO v1.0.0 (Is it up to date?)
java.lang.NoClassDefFoundError: org/bukkit/craftbukkit/v1_19_R1/CraftServer
	at libs.com.karuslabs.commons.command.dispatcher.Dispatcher.of(Dispatcher.java:77) ~[_papermake_hooked_JtFUwtSJVIRD5jjJeIoV9vizPkRRJqtH.jar:?]
	at io.github.alchemy_io.alchemyio.commands.AIOCommands.registerCommands(AIOCommands.java:9) ~[_papermake_hooked_JtFUwtSJVIRD5jjJeIoV9vizPkRRJqtH.jar:?]
	at io.github.alchemy_io.alchemyio.AlchemyIO.onEnable(AlchemyIO.java:37) ~[_papermake_hooked_JtFUwtSJVIRD5jjJeIoV9vizPkRRJqtH.jar:?]
	at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:279) ~[paper-api-1.19.3-R0.1-SNAPSHOT.jar:?]
	at io.papermc.paper.plugin.manager.PaperPluginInstanceManager.enablePlugin(PaperPluginInstanceManager.java:192) ~[paper-1.19.3.jar:git-Paper-426]
	at io.papermc.paper.plugin.manager.PaperPluginManagerImpl.enablePlugin(PaperPluginManagerImpl.java:104) ~[paper-1.19.3.jar:git-Paper-426]
	at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:507) ~[paper-api-1.19.3-R0.1-SNAPSHOT.jar:?]
	at org.bukkit.craftbukkit.v1_19_R2.CraftServer.enablePlugin(CraftServer.java:561) ~[paper-1.19.3.jar:git-Paper-426]
	at org.bukkit.craftbukkit.v1_19_R2.CraftServer.enablePlugins(CraftServer.java:472) ~[paper-1.19.3.jar:git-Paper-426]
	at net.minecraft.server.dedicated.DedicatedServer.initServer(DedicatedServer.java:274) ~[paper-1.19.3.jar:git-Paper-426]
	at net.minecraft.server.MinecraftServer.runServer(MinecraftServer.java:1101) ~[paper-1.19.3.jar:git-Paper-426]
	at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:316) ~[paper-1.19.3.jar:git-Paper-426]
	at java.lang.Thread.run(Thread.java:833) ~[?:?]
Caused by: java.lang.ClassNotFoundException: org.bukkit.craftbukkit.v1_19_R1.CraftServer
	at org.bukkit.plugin.java.PluginClassLoader.loadClass0(PluginClassLoader.java:181) ~[paper-api-1.19.3-R0.1-SNAPSHOT.jar:?]
	at org.bukkit.plugin.java.PluginClassLoader.loadClass(PluginClassLoader.java:148) ~[paper-api-1.19.3-R0.1-SNAPSHOT.jar:?]
	at java.lang.ClassLoader.loadClass(ClassLoader.java:520) ~[?:?]
	... 13 more
```

**Comment by Pante** [comment]
Ah I wasn’t aware they released a new NMS version. The last verified working version is 1.19.1. 

I’ll probably release an update sometime next week. I currently don’t access to my machine.

**Comment by qyl27** [comment]
oh, thanks for your fast reply and waiting for further update.

**Comment by Pante** [comment]
I've release 5.5.0 which should work on 1.19.3.
